name: NaturalTrees
version: 1.1.0
main: de.TrustedCreeper.NaturalTrees.NaturalTrees
author: TrustedCreeper
website: http://TrustedCreeper.de/
softdepend: [WorldEdit, WorldGuard]
commands:
    nt:
        description: NaturalTrees
        usage: /<command>
